server:
  port: 8080

spring:
  cloud:
    gateway:
      httpserver:
        wiretap: false
      httpclient:
        wiretap: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://labsys.frc.utn.edu.ar/aim/realms/backend-tps

microservicios:
  vehiculos: http://localhost:8081
  interesados: http://localhost:8082
  notificaciones: http://localhost:8083