server:
  port: 8080

spring:
  cloud:
    gateway:
      httpserver:
        wiretap: false
      httpclient:
        wiretap: false

microservicios:
  vehiculos: http://localhost:8081
  interesados: http://localhost:8082